startup:
  initRate: false

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10000

rate:
  cache:
    expire: 3600
  scheduled:
    cron: 0 0 0/1 * * ?

provider:
  CurrencyLayer:
    enable: true
    username:
    key:
    plan:
  OneForge:
    enable: true
    username:
    key:
    plan:
  EuropeanCentralBank:
    enable: true
  OpenExchangeRates:
    enable: true
    username:
    key:
    plan: